### ISSUE TITLE
power buttons under search bar 

### ISSUE THREAD

**Issue by Moshe-Shelomov** [HimDek/Simple-Kickoff-for-Plasma#14]
what the title says, buttons for restart, power off etc are sitting under searchbar and therefore are unreachable

I am using Endeavour OS (arch based) and kde 6
downloaded the plasmoid from kde store and installed via the command provided here on github with minor change that seemed logical to me: (kpackagetool6 -t Plasma/Applet --install)

![изображение](https://github.com/HimDek/Simple-Kickoff-for-Plasma/assets/142827019/b8208fe0-e2ed-4e93-8b9b-8eccb476f081)

**Comment by HimDek** [comment]
#10  and #9
