### ISSUE TITLE
[Feature Request] Add option to stop categories from activating on mouseover.

### ISSUE THREAD

**Issue by niobium93** [HimDek/Simple-Kickoff-for-Plasma#2]
I find the fact that the categories switch on mouseover very annoying, to the point where I just can't use the Kickoff menu. I just end up trying to click something in my favorites while the category changes to something else because I moved my mouse over it too slowly... It would be nice if it was possible to disable this behavior in the configuration. To have to actually click on the categories to switch between them.

Thanks for your work and consideration :)

**Comment by HimDek** [comment]
This feature has been added with https://github.com/HimDek/Simple-Kickoff-for-Plasma/commit/f9ea591e8e88057d6a00ede757f25fb2fcd7a8ed. Published in version 2.5. Get it from [KDE Store](https://store.kde.org/p/1819888/)
