### ISSUE TITLE
Width compensation to avoid resizing when scrolling is available

### ISSUE THREAD

**Issue by hz61p1** [HimDek/Simple-Kickoff-for-Plasma#5]
When moving from a category with few apps to a category with many apps, the appearance of the scrollbar causes a resize. 

https://github.com/HimDek/Simple-Kickoff-for-Plasma/assets/12779610/720763da-d04d-4e8e-bd97-697cfcf3a8c0

**Comment by HimDek** [comment]
This issue is fixed in the latest versions for Plasma 6.
